name: SF Uploader
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
            
       - name: Download Build
         run: |
            source device_and_download_link
            if [[ $download_link == *"drive.google.com"* ]]; then
            pip install gdown
            if [[ $download_link == *"file"* ]]; then
            download_link=$(echo $download_link | cut -d / -f 6)
            elif [[ $download_link == *"id"* ]]; then
            download_link1=$(echo $download_link | cut -d = -f 2 | cut -d '&' -f 1)
            download_link2=$(echo $download_link | cut -d = -f 4)
            fi
            gdown https://drive.google.com/uc?id=$download_link1 || gdown https://drive.google.com/uc?id=$download_link2
            else
            aria2c -c -m0 -x16 -s50 $download_link
            fi
              
       - name: Upload To SF
         run: |
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"     
    - name: Upload in SourceForge
      run: |
            source device_and_download_link
            rsync -vhcP -e ssh realme6seriesdownloads* thecloverly@frs.sourceforge.net:/home/frs/project/realme6seriesdownloads/eleven/$device/
